# Generated by Django 3.0.1 on 2020-06-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsphoto', models.ImageField(upload_to='')),
                ('headline', models.CharField(max_length=100)),
                ('news', models.CharField(max_length=1000)),
                ('photo', models.ImageField(upload_to='')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('othernews1', models.ImageField(upload_to='')),
            ],
        ),
    ]
