# Generated by Django 3.0.1 on 2020-06-27 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbluser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(blank=True, max_length=500)),
                ('nickname', models.CharField(blank=True, max_length=500)),
                ('City', models.CharField(blank=True, max_length=100)),
                ('profilephoto', models.ImageField(blank=True, upload_to='')),
                ('backgroundphoto', models.ImageField(blank=True, upload_to='')),
                ('Membership', models.CharField(default='No', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
