# Generated by Django 3.0.1 on 2020-06-27 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manganame', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('file', models.CharField(max_length=100)),
                ('information', models.CharField(max_length=500)),
            ],
        ),
    ]
